#Creating and Importing trtl
import turtle as trtl
drawer = trtl.Turtle()

drawer.speed(0)

#Creating the first rectangle
drawer.begin_fill()
drawer.penup()
drawer.goto(0,-100)
drawer.pendown()
drawer.forward(20)
drawer.left(90)
drawer.forward(150)
drawer.left(45)
drawer.forward(15)
drawer.left(45)
drawer.left(45)
drawer.forward(15)
drawer.left(45)
drawer.forward(150)
drawer.end_fill()
#Creating the second rectangle
drawer.begin_fill()
drawer.penup()
drawer.goto(20,50)
drawer.pendown()
drawer.left(135)
drawer.forward(75)
drawer.left(90)
drawer.forward(15)
drawer.left(90)
drawer.forward(75)
drawer.end_fill()
#Creating the third rectangle
drawer.begin_fill()
drawer.right(90)
drawer.forward(75)
drawer.left(90)
drawer.forward(15)
drawer.left(90)
drawer.forward(75)
drawer.end_fill()
#Creating the string
drawer.pencolor("red")
drawer.penup()
drawer.goto(-50,109)
drawer.pendown()
drawer.left(20)
drawer.forward(150)
drawer.circle(20,180)
drawer.right(10)
drawer.forward(50)
#Creates the ball
drawer.begin_fill()
drawer.penup()
drawer.goto(105,55)
drawer.pendown()
drawer.circle(5)
drawer.end_fill()

#Clears screen and resets everything
drawer.clear()

drawer.penup()
drawer.goto(0,0)
drawer.setheading(0)


#Creating the first rectangle
drawer.begin_fill()
drawer.penup()
drawer.goto(0,-100)
drawer.pendown()
drawer.forward(20)
drawer.left(90)
drawer.forward(150)
drawer.left(45)
drawer.forward(15)
drawer.left(45)
drawer.left(45)
drawer.forward(15)
drawer.left(45)
drawer.forward(150)
drawer.end_fill()
#Creating the second rectangle
drawer.begin_fill()
drawer.penup()
drawer.goto(20,50)
drawer.pendown()
drawer.left(135)
drawer.forward(75)
drawer.left(90)
drawer.forward(15)
drawer.left(90)
drawer.forward(75)
drawer.end_fill()
#Creating the third rectangle
drawer.begin_fill()
drawer.right(90)
drawer.forward(75)
drawer.left(90)
drawer.forward(15)
drawer.left(90)
drawer.forward(75)
drawer.end_fill()
#Creating the string
drawer.pencolor("red")
drawer.penup()
drawer.goto(-50,109)
drawer.pendown()
drawer.left(30)
drawer.forward(100)
drawer.circle(15,180)
drawer.right(10)

#Creates the ball
drawer.begin_fill()
drawer.penup()
drawer.goto(60,100)
drawer.pendown()
drawer.circle(5)
drawer.end_fill()

#Clears screen and resets everything
drawer.clear()

drawer.penup()
drawer.goto(0,0)
drawer.setheading(0)


#Creating the first rectangle
drawer.begin_fill()
drawer.penup()
drawer.goto(0,-100)
drawer.pendown()
drawer.forward(20)
drawer.left(90)
drawer.forward(150)
drawer.left(45)
drawer.forward(15)
drawer.left(45)
drawer.left(45)
drawer.forward(15)
drawer.left(45)
drawer.forward(150)
drawer.end_fill()
#Creating the second rectangle
drawer.begin_fill()
drawer.penup()
drawer.goto(20,50)
drawer.pendown()
drawer.left(135)
drawer.forward(75)
drawer.left(90)
drawer.forward(15)
drawer.left(90)
drawer.forward(75)
drawer.end_fill()
#Creating the third rectangle
drawer.begin_fill()
drawer.right(90)
drawer.forward(75)
drawer.left(90)
drawer.forward(15)
drawer.left(90)
drawer.forward(75)
drawer.end_fill()
#Creating the string
drawer.pencolor("red")
drawer.penup()
drawer.goto(-50,109)
drawer.pendown()
drawer.left(70)
drawer.forward(50)
drawer.circle(-15,60)
drawer.left(10)
drawer.forward(50)
#Creates the ball
drawer.begin_fill()
drawer.penup()
drawer.goto(-20,150)
drawer.pendown()
drawer.circle(5)
drawer.end_fill()

drawer.hideturtle()


wn = trtl.Screen()
wn.mainloop()                                                                                                                                                                                                                   